// THIS FILE IS AUTOGENERATED. DO NOT EDIT
/* eslint-disable */
/* tslint:disable */
export const noop = () => {}
import * as useAnimationForever from './useAnimationForever'
export { useAnimationForever }